from pathlib import Path
import html,json,os

ROOT=Path(__file__).parent
OUT=ROOT
PAGES={}
def add(slug,title,group,lead,heading,text,features=None):
 PAGES[slug]=dict(title=title,group=group,lead=lead,heading=heading,text=text,features=features or [])
add('it-dienstleistungen','IT-Dienstleistungen','IT','Eine IT-Umgebung, die zu Ihrem Unternehmen passt. Von der ersten Idee bis zur laufenden Betreuung.','Für Ihren Arbeitsalltag. Für Ihre nächsten Schritte.','Netzwerke, Serversysteme, Arbeitsplätze und Kommunikation gehören zusammen. Wir unterstützen Sie bei der Planung und Umsetzung Ihrer IT und begleiten Sie auch im laufenden Betrieb.')
add('beratung','IT-Beratung','IT','Gute Entscheidungen beginnen mit einem klaren Blick auf Ihre Anforderungen.','Erst verstehen. Dann sinnvoll planen.','Wir beraten Sie bereits vor der Umsetzung Ihrer IT-Projekte. Gemeinsam entwickeln wir eine Netzwerkumgebung, die zu Ihrem Betrieb, Ihren Anforderungen und Ihrem Budget passt.', [('Anforderungen klären','Welche Arbeitsabläufe soll die IT unterstützen? Wir bringen Ihre Ziele und die technischen Möglichkeiten zusammen.'),('Umgebung konzipieren','Eine durchdachte Planung verbindet Netzwerk, Arbeitsplätze und Anwendungen zu einer passenden Lösung.'),('Umsetzung vorbereiten','Eine nachvollziehbare Konzeption schafft die Grundlage für die nächsten Projektschritte.')])
add('msp-dienste','Managed Services','IT','Ihre Systeme betreut. Ihre Mitarbeiter entlastet. IT-Dienste, die sich an Ihrem Bedarf orientieren.','Mehr Freiraum für Ihr Unternehmen.','Als Managed Service Provider stellen wir Dienste bereit und betreuen Ihre Serversysteme. Vom modernen Arbeitsplatz bis zur Sicherung wichtiger Daten erhalten Sie aufeinander abgestimmte Lösungen.', [('Microsoft 365 & Exchange Online','Zusammenarbeit, E-Mail und Office-Anwendungen für Büro und mobiles Arbeiten.'),('Managed Backup','Datensicherung für virtuelle Maschinen, Microsoft-365-Daten und E-Mail-Postfächer.'),('E-Mail-Archivierung','Zentrale Erfassung und Archivierung Ihrer E-Mail-Kommunikation.'),('E-Mail-Sicherheit','Schutz Ihrer Kommunikation vor Spam und Schadsoftware.'),('Infrastruktur & Monitoring','Bereitstellung, Wartung und Überwachung kritischer Systeme.'),('Telefonie & Security','Cloud-Telefonanlagen und Verwaltung von Endpoints, Firewalls und weiteren Systemen.')])
add('netzwerkbetreuung','Netzwerkbetreuung','IT','Die Verbindung zwischen Ihren Menschen, Standorten und Anwendungen.','Damit Informationen zuverlässig ankommen.','Ihr Netzwerk ist die Grundlage für Daten und Kommunikation. Unsere Betreuung umfasst Auswahl, Installation, Administration, Fehlersuche, Sicherheit und Wartung. Gemeinsam betrachten wir Ihre gesamte Netzwerkumgebung.', [('Planung & Installation','Passende Komponenten und ein nachvollziehbarer Aufbau Ihrer Infrastruktur.'),('Administration & Sicherheit','Betreuung der Systeme und Unterstützung bei Fragen zur Netzwerksicherheit.'),('Fehlersuche & Wartung','Technische Probleme verstehen und Ihre Umgebung im laufenden Betrieb begleiten.')])
add('hard_und_software','Hard- & Software','IT','Passende Technik für Ihren Arbeitsplatz. Vorbereitet, eingerichtet und betreut.','Ein Arbeitsplatz, der zu Ihnen passt.','Wir bieten Computersysteme, Netzwerkprodukte, Drucker, Zubehör, Telefonie und Software ausgewählter Hersteller. Die Vorbereitung erfolgt bei uns; die Installation bei Ihnen vor Ort oder per Fernwartung.', [('Hardware & Zubehör','Computersysteme, Monitore, Drucker und Netzwerkkomponenten für Ihren Bedarf.'),('Software & Lizenzen','Anwendungen und Microsoft-365-Lösungen passend zu Ihren Arbeitsabläufen.'),('Workplace as a Service','Hardware und Service als Mietmodell mit planbaren monatlichen Ausgaben. Umfang und Konditionen klären wir persönlich.')])
add('tk_anlagen','Telekommunikation','IT','Erreichbar bleiben. Im Büro, unterwegs und im Homeoffice.','Kommunikation ohne unnötige Umwege.','Wir beraten Sie bei der Auswahl Ihrer Telefonanlage und begleiten die Umsetzung. Moderne VoIP- und softwarebasierte Lösungen schaffen flexible Möglichkeiten. Auch nach der Einrichtung stehen unsere Techniker vor Ort oder per Fernwartung zur Verfügung.', [('Passendes System','Ihre Arbeitsweise und die Größe Ihres Unternehmens bestimmen die Lösung.'),('Installation & Einrichtung','Eine abgestimmte Umsetzung integriert die Telefonie in Ihre Umgebung.'),('Persönliche Betreuung','Unterstützung im Bedarfsfall und Begleitung nach dem Projektabschluss.')])
add('sicherheitstechnik','Sicherheitstechnik','Sicherheit','Menschen, Gebäude und Werte schützen. Mit Technik, die sinnvoll zusammenspielt.','Ihr Schutz beginnt mit dem richtigen Konzept.','Wir verbinden Beratung mit individuellen Lösungen für Videoüberwachung, Einbruch- und Brandmeldetechnik, Zutrittskontrollen und Zeiterfassung. Entscheidend sind Ihr Standort, Ihre Abläufe und Ihre Anforderungen.')
add('beratung-35','Sicherheitsberatung','Sicherheit','Ein Sicherheitskonzept muss zu Ihren tatsächlichen Anforderungen passen.','Durchdacht statt einzeln betrachtet.','Unsere Erfahrung in Videoüberwachung, Gefahrenmeldetechnik, Zutrittskontrollen und Zeiterfassung fließt in Ihre Planung ein. Gemeinsam besprechen wir, welche Lösung für Ihr Unternehmen sinnvoll ist.', [('Bedarf verstehen','Gebäude, Nutzung und die schützenswerten Bereiche gemeinsam betrachten.'),('Systeme abstimmen','Video, Alarmierung und Zutritt als zusammenhängende Lösung planen.'),('Qualität berücksichtigen','Eine passende Konzeption bildet die Grundlage für die technische Umsetzung.')])
add('kamerasysteme','Kamerasysteme','Sicherheit','Überblick behalten. Bereiche gezielt überwachen. Sicherheit sichtbar machen.','Sehen, was für Sie wichtig ist.','Videoüberwachung kann Personen und Sachwerte schützen, vorbeugend wirken und die Aufklärung von Schadensereignissen unterstützen. Wir beraten Sie zu passenden IP-Kamerasystemen für unterschiedliche Einsatzbereiche.', [('Gezielter Einsatz','Eingänge, Außenbereiche oder sensible Zonen abhängig vom Bedarf betrachten.'),('IP-Videotechnik','Vernetzte Kamerasysteme mit einer auf Ihren Standort abgestimmten Konfiguration.'),('Systemintegration','Videoüberwachung als Teil Ihrer Gebäudesicherung planen.')])
add('einbruchmeldeanlagen','Einbruchmeldeanlagen','Sicherheit','Vom einzelnen Bereich bis zur abgestimmten Gebäudesicherung.','Eindringen erkennen. Reaktion ermöglichen.','Nach einer Bedarfsanalyse planen wir eine passende Absicherung. Bewegungsmelder und weitere Komponenten erkennen Eindringen oder Einbruchsversuche. Je nach Konzept kann eine örtliche Alarmierung oder die Anbindung an eine Notruf- und Serviceleitstelle vorgesehen werden.', [('Individuelle Absicherung','Schutz für Räume, Gebäude oder einzelne Objekte.'),('Alarmierung vor Ort','Akustische und optische Signale als Teil des Schutzkonzepts.'),('Vernetzte Sicherheit','Eine mögliche Verbindung mit Zutrittskontrolle und Videotechnik gemeinsam betrachten.')])
add('brandmeldeanlagen','Brandmeldeanlagen','Sicherheit','Brände frühzeitig erkennen. Betroffene Personen informieren. Alarmierung ermöglichen.','Technischer Brandschutz mit Verantwortung.','Brandmeldeanlagen unterstützen die frühe Erkennung und Lokalisierung entstehender Brände. Wir begleiten Sie bei Fragen zur Brandmeldetechnik und besprechen die Anforderungen Ihrer Anlage, von der Planung bis zur Betreuung.', [('Früherkennung','Geeignete Melder und ein auf das Gebäude abgestimmtes Konzept.'),('Alarmierung','Information und Alarmierung als Teil des technischen Brandschutzes.'),('Fachliche Betreuung','Projektbezogene Anforderungen, Wartung und Zuständigkeiten persönlich klären.')])
add('zutrittkontrollen','Zutrittskontrollen','Sicherheit','Sie entscheiden, wer wann welchen Bereich betreten darf.','Zugang gezielt steuern.','Elektronische Zutrittssysteme ermöglichen individuelle Berechtigungen für Türen, Tore und Durchgänge. Berechtigungen lassen sich ändern oder entfernen, etwa beim Verlust eines Transponders. Eine Vernetzung mit Alarm- und Videotechnik kann sinnvoll sein.', [('Berechtigungen','Personen, Bereiche und Zeitfenster gezielt verwalten.'),('Flexibel reagieren','Zugänge bei Änderungen oder verlorenen Zutrittsmedien anpassen.'),('Vernetzbar erweitern','Mehrere Zugänge und weitere Sicherheitssysteme gemeinsam betrachten.')])
add('zeiterfassung','Zeiterfassungssysteme','Sicherheit','Arbeitszeiten, Projektzeiten und Abwesenheiten nachvollziehbar erfassen.','Mehr Überblick im Arbeitsalltag.','Wir suchen gemeinsam mit Ihnen eine Lösung, die zu Ihren Abläufen passt. Konfiguration, Erweiterungen und individuelle Auswertungen unterstützen die täglichen Anforderungen Ihres Unternehmens.', [('Arbeitszeiten','Zeiten und Abwesenheiten transparent erfassen.'),('Projektbezug','Projektzeiten als zusätzliche Grundlage für Ihre Auswertungen.'),('Individuelle Einrichtung','Anforderungen und zusätzliche Funktionen gemeinsam abstimmen.')])
add('datenschutzbetreuung','Datenschutzbetreuung','Datenschutz','Mehr Klarheit beim Umgang mit Daten. Gemeinsam mit fachlicher Unterstützung.','Datenschutz verständlich begleiten.','In Zusammenarbeit mit documentus Bayern verbindet SL Service IT-Know-how mit Datenschutzberatung. Die Betreuung unterstützt Sie dabei, den aktuellen Stand zu erfassen, Maßnahmen zu planen und Ihre Mitarbeiter einzubeziehen.', [('Bestandsaufnahme','Einführungsgespräch, IST-Analyse und Bewertung Ihrer vorhandenen Standards.'),('Maßnahmen planen','Ein nachvollziehbarer Katalog und Unterstützung bei technischen Fragestellungen.'),('Menschen einbeziehen','Ansprechpartner, wiederkehrende Schulungen und Unterstützung im Beschwerdefall.'),('Passende Betreuung','Umfang und Zusammenarbeit richten sich nach Ihrem Bedarf. Die Umsetzung von Maßnahmen bleibt Ihre Entscheidung.')])
add('sl-service','SL Service','Unternehmen','Ihr regionales Systemhaus für IT, Kommunikation und Sicherheitstechnik.','Technik verstehen. Unternehmen begleiten.','Seit 2003 unterstützt SL Service kleine und mittelständische Unternehmen in der Region. Unser Leistungsspektrum verbindet die Betreuung Ihrer IT-Umgebung mit Telekommunikation sowie Gebäude- und Grundstückssicherheit.')
add('kompetenz','Unsere Kompetenz','Unternehmen','Ihr Bedarf steht im Mittelpunkt. Unser Know-how verbindet die passenden technischen Bereiche.','Aus einzelnen Aufgaben wird eine Lösung.','Wir planen Ihre Netzwerkumgebung und unterstützen Sie bei Ihren IT-Aufgaben. Gleichzeitig beraten wir Sie zur Sicherheitstechnik Ihres Unternehmens. So können technische Fragen gemeinsam und im Zusammenhang betrachtet werden.', [('IT & Kommunikation','Netzwerke, Hard- und Software und Telefonanlagen aufeinander abstimmen.'),('Gebäudesicherheit','Passende Lösungen für Überwachung, Alarmierung und Zutritt betrachten.'),('Persönliche Beratung','Ihre Anforderungen sind der Ausgangspunkt für eine sinnvolle Planung.')])
add('vorstellung','Das Unternehmen','Unternehmen','Regional verbunden. Technisch vielseitig. Seit 2003 an der Seite Ihrer Unternehmen.','SL Service kennenlernen.','SL Service unterstützt kleine und mittelständische Unternehmen aus der Region bei Netzwerkbetreuung, Hard- und Software, Telekommunikation und Sicherheitstechnik. Unser Standort befindet sich am Innovativ-Ring 1 in Dinkelsbühl.', [('Breites Leistungsspektrum','IT-Arbeitsplätze, Kommunikationslösungen und Gebäudesicherheit.'),('Technisches Know-how','Beratung, Konfiguration, Umsetzung und Betreuung Ihrer Systeme.'),('Direkte Ansprechpartner','Lernen Sie die Verantwortlichen für Ihre Anliegen kennen.')])
add('sl-service/branchen-loesungen','Branchen & Lösungen','Unternehmen','Unterschiedliche Branchen. Unterschiedliche Anforderungen. Eine passende technische Lösung.','Ihre Arbeitswelt ist unser Ausgangspunkt.','SL Service betreut IT-Umgebungen und Sicherheitstechnik unter anderem für Handwerk, Industrie, Handel, Gastronomie und Hotellerie, öffentliche und kirchliche Institutionen, Stadt- und Gemeindeverwaltungen sowie Arztpraxen.')
add('karriere','Karriere bei SL Service','Unternehmen','Bringen Sie Ihr Know-how ein. Entwickeln Sie sich weiter. Gestalten Sie Technik im Team.','Ihre Ideen. Unser gemeinsamer Weg.','Wir freuen uns über Menschen, die ihre Erfahrung und Begeisterung für Technik einbringen möchten. Neben der auf der bestehenden Website vorgestellten Ausbildung sind auch Initiativbewerbungen willkommen.')
add('job/ausbildung-elektroniker-in-fuer-gebaeude-und-infrastruktursysteme-m-w-d','Ausbildung Elektroniker/in','Karriere','Für Geräte und Systeme · m/w/d · Dinkelsbühl','Technik praktisch lernen.','Die auf der bestehenden Website vorgestellte duale Ausbildung dauert 3,5 Jahre. Sie beschäftigt sich mit Gefahrenmeldetechnik, Videoüberwachung und Zutrittskontrollen. Bitte fragen Sie den aktuellen Ausbildungsbeginn und die Verfügbarkeit direkt an.', [('Ihre Aufgaben','Sicherheits- und Brandmeldesysteme planen, konfigurieren und betreuen. Probleme diagnostizieren und an Projekten mitarbeiten.'),('Ihr Profil','Neugier, Teamgeist und verantwortungsvolles Arbeiten. Ein mittlerer Bildungsabschluss ist von Vorteil; sehr gute Deutschkenntnisse werden erwartet.'),('Ihre Entwicklung','Ein kollegiales Umfeld, abwechslungsreiche Aufgaben und abgestimmte Weiterbildungen begleiten die Ausbildung.')])
add('kontakt','Kontakt','Kontakt','Eine Frage, ein Projekt oder ein technisches Anliegen? Wir sind gerne für Sie da.','Sprechen wir miteinander.','SL Service und Verwaltungs GmbH · Innovativ-Ring 1 · 91550 Dinkelsbühl')
add('kontaktformular','Kontaktformular','Kontakt','Beschreiben Sie Ihr Anliegen. Wir bereiten Ihre Nachricht für Ihr E-Mail-Programm vor.','Was dürfen wir für Sie tun?','Diese Präsentationsversion versendet keine Nachrichten im Hintergrund.')
add('ansprechpartner','Ihre Ansprechpartner','Kontakt','Direkte Wege für Ihr Anliegen. Finden Sie den passenden Kontakt.','Persönlich erreichbar.','Hier finden Sie die auf der bestehenden Website genannten Ansprechpartner für Geschäftsführung, Organisation, IT und Sicherheitstechnik.')
add('standort','Unser Standort','Kontakt','Am Innovativ-Ring 1 in Dinkelsbühl. Wir freuen uns auf das Gespräch mit Ihnen.','Ihr Weg zu SL Service.','Innovativ-Ring 1, Waldeck · 91550 Dinkelsbühl. Vereinbaren Sie gerne vor Ihrem Besuch einen Termin.')
add('support','Support & Fernwartung','Kontakt','Schnelle Wege bei technischen Fragen. Telefonisch, per E-Mail oder nach Absprache per Fernwartung.','Direkt zu Ihrer Unterstützung.','Bei technischen Problemen, Fragen zu Hard- und Software oder für einen Vor-Ort-Termin erreichen Sie das Support-Team während der angegebenen Servicezeiten.')
add('Backup','Backup-as-a-Service','IT','Datensicherung, die zu Ihrer Umgebung passt.','Wichtige Daten im Blick behalten.','SL Service unterstützt Sie bei Sicherungskonzepten, Auswahl der Hardware und Umsetzung. Individuell abgestimmte Backups helfen beim Umgang mit versehentlichem Löschen, Hardwarefehlern oder Schadsoftware.', [('Konzept & Umsetzung','Passende Sicherungsziele und Systeme gemeinsam besprechen.'),('Verwaltung & Wiederherstellung','Betreuung Ihrer Sicherungen und Möglichkeiten zur Wiederherstellung.'),('Individuelle Konditionen','Aktuelle Leistungen und Preise erhalten Sie im persönlichen Gespräch; frühere Archivpreise werden hier nicht als aktuelles Angebot verwendet.')])

IT=['beratung','msp-dienste','netzwerkbetreuung','hard_und_software','tk_anlagen']
SEC=['beratung-35','kamerasysteme','einbruchmeldeanlagen','brandmeldeanlagen','zutrittkontrollen','zeiterfassung']
COMP=['kompetenz','vorstellung','sl-service/branchen-loesungen','karriere']
CONTACT=['ansprechpartner','kontaktformular','standort','support']
ARTICLES=[
('news/videoueberwachung-als-erweiterung-ihrer-einbruchmeldeanlage','Videoüberwachung als Erweiterung Ihrer Einbruchmeldeanlage','11.01.2024','Sicherheit','Kameras ergänzen die Gebäudesicherung.','kamerasysteme'),
('news/die-sl-mitarbeiter-spenden-fuer-den-dinkelsbuehler-tisch','Die SL-Mitarbeiter spenden für den Dinkelsbühler Tisch','21.12.2023','Unternehmen','Engagement für den Dinkelsbühler Tisch.','sl-service'),
('news/spatenstich-beim-technologie-campus-dinkelsbuehl','Spatenstich beim Technologie Campus Dinkelsbühl','09.10.2023','Unternehmen','SL Service und SL innovativ engagierten sich beim Start des Technologie Campus. Das spendenfinanzierte Projekt sollte Kindern und Jugendlichen praktische Zugänge zu moderner Technik ermöglichen.','sl-service'),
('news/fahrradfahren-na-klar/articles/272','Fahrradfahren – na klar!','21.06.2023','Unternehmen','Sicherheitstraining auf dem Fahrrad.','sl-service'),
('news/hoffest-2023','Hoffest 2023 – 20 Jahre SL Service','26.05.2023','Unternehmen','Am 25. Mai 2023 feierte SL Service sein 20-jähriges Jubiläum mit Gästen und Partnern. Fachvorträge zu Cyberkriminalität, Kameraüberwachung und E-Mail-Sicherheit ergänzten das gemeinsame Hoffest.','vorstellung'),
('news/feueralarm-wie-sie-sich-richtig-verhalten','Feueralarm: Wie Sie sich richtig verhalten','25.01.2023','Sicherheit','Der archivierte Beitrag behandelt Verhalten bei Brandalarm und die Bedeutung von Fluchtwegen und Sammelpunkten. Bitte beachten Sie die Alarm- und Sicherheitsanweisungen Ihres Gebäudes sowie die Anweisungen der Einsatzkräfte.','brandmeldeanlagen'),
('news/axis-partnerschaft-kameras-fuer-jeden-einsatzbereich','Axis Partnerschaft: Kameras für jeden Einsatzbereich','14.07.2022','Sicherheit','Kameralösungen für unterschiedliche Einsatzbereiche.','kamerasysteme'),
('news/erster-virtueller-infotag-am-11-november-2021','Unser erster virtueller Infotag','15.11.2021','Unternehmen','Einblicke in IT-Dienstleistungen und Datenschutz.','sl-service'),
('news/workplace-as-a-service','Workplace as a Service','05.05.2021','IT','Arbeitsplatztechnik als Mietmodell.','hard_und_software'),
('news/microsoft-silver-partner','Microsoft Silver Partner','17.02.2021','IT','Historischer Einblick in Microsoft-Kompetenzen.','msp-dienste'),
('news/datenschutzbetreuung','Datenschutzbetreuung','12.11.2020','IT','Begleitung beim Umgang mit Daten.','datenschutzbetreuung'),
('news/testyourmobotix','TestYourMobotix','28.05.2020','Sicherheit','Konfiguration eines vorhandenen Videosystems.','kamerasysteme')]

def esc(s):return html.escape(s,quote=True)
def href(slug,base):return base+('index.html' if not slug else 'de/'+slug+'.html')
def link(slug,base,label=None,cls=''):
 title=label or PAGES[slug]['title']
 return f'<a class="{cls}" href="{href(slug,base)}">{title}</a>'
def btn(slug,base,label,outline=False):return f'<a class="btn {"btn-outline" if outline else ""}" href="{href(slug,base)}">{label}<span class="arrow" aria-hidden="true">↗</span></a>'
def brand(base):return f'<a class="brand" href="{href("",base)}" aria-label="SL Service – Startseite"><img src="{base}assets/brand-reference.png" alt="SL Service" width="1173" height="318"></a>'
def header(base,current):
 groups=[('it-dienstleistungen','IT-Dienstleistungen',IT),('datenschutzbetreuung','Datenschutzbetreuung',[]),('sicherheitstechnik','Sicherheitstechnik',SEC),('sl-service','Unternehmen',COMP),('kontakt','Kontakt',CONTACT)]
 desktop='';mobile=''
 for i,(slug,title,children) in enumerate(groups):
  a=f'<a href="{href(slug,base)}" {"aria-current=page" if current==slug else ""}>{title}</a>'
  sub=''.join(link(x,base) for x in children)
  if slug=='sl-service':sub+=f'<a href="{href("news",base)}">Blog & Archiv</a>'
  desktop+=f'<div class="nav-group">{a}'+(f'<button class="nav-toggle" aria-label="Unterseiten {title}" aria-expanded="false" aria-controls="nav-{i}">⌄</button><div class="dropdown" id="nav-{i}">{link(slug,base,"Übersicht →")}{sub}</div>' if children else '')+'</div>'
  mobile+=(f'<details><summary>{title}</summary><div>{link(slug,base,"Übersicht →")}{sub}</div></details>' if children else a)
 return f'<a class="skip" href="#inhalt">Zum Inhalt springen</a><header class="header"><div class="wrap header-inner">{brand(base)}<nav class="desktop-nav" aria-label="Hauptnavigation">{desktop}</nav><button class="btn" data-support>Support <span aria-hidden="true">↗</span></button><button class="menu-button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Menü öffnen">☰</button></div><nav class="mobile-nav" id="mobile-menu" aria-label="Mobile Navigation" hidden>{mobile}<a href="{href("news",base)}">Blog & Archiv</a></nav></header>'
def footer(base):
 return f'''<footer class="footer"><div class="wrap footer-top"><div><a class="footer-wordmark" href="{href('',base)}">SL SERVICE<span class="dot">.</span></a><p>IT, Kommunikation und Sicherheitstechnik.<br>Persönlich. Regional. Kompetent.</p><p>SL Service und Verwaltungs GmbH<br>Innovativ-Ring 1 · 91550 Dinkelsbühl</p></div><div><h3>Unsere Leistungen</h3><nav>{link('it-dienstleistungen',base)}{link('sicherheitstechnik',base)}{link('datenschutzbetreuung',base)}{link('msp-dienste',base)}</nav></div><div><h3>Das Unternehmen</h3><nav>{link('vorstellung',base)}{link('sl-service/branchen-loesungen',base)}{link('karriere',base)}{link('news',base,'Blog & Archiv')}{link('ansprechpartner',base)}</nav></div><div><h3>Direkt verbunden</h3><nav><a href="tel:+4998515825890">09851 58258-90</a><a href="mailto:info@sl-sv.de">info@sl-sv.de</a>{link('support',base)}{link('standort',base)}</nav><p>Mo–Do 08:00–16:00 Uhr<br>Fr 08:00–14:00 Uhr</p></div></div><div class="wrap footer-bottom"><span>© 2026 SL Service · Website-Entwurf</span><nav>{link('impressum',base,'Impressum')}{link('datenschutz',base,'Datenschutz')}{link('agb',base,'AGB')}<a href="#inhalt">Nach oben ↑</a></nav></div><div class="wrap concept-note"><span class="demo-mark">Designkonzept zur Kundenvorstellung</span> · Bildmotive sind illustrative KI-generierte Konzeptbilder, keine Aufnahmen des Unternehmens. Konzept & Umsetzung: Kaiser Webdesign.</div></footer>'''
def support(base):return f'''<dialog class="support-dialog" id="support-dialog" aria-labelledby="support-title"><div class="dialog-inner"><button class="dialog-close" aria-label="Support schließen">×</button><p class="eyebrow">Ihr direkter Draht</p><h2 id="support-title">Wir helfen<br>gerne weiter<span class="dot">.</span></h2><p>Bei technischen Fragen oder für einen Vor-Ort-Termin.</p><a class="contact-detail" href="tel:+4998515825890">09851 58258-90 ↗</a><a href="mailto:support@sl-sv.de">support@sl-sv.de</a><div class="hours"><span>Montag–Donnerstag</span><span>08:00–16:00</span><span>Freitag</span><span>08:00–14:00</span></div>{btn('support',base,'Support & Fernwartung')}</div></dialog>'''
def cta(base):return f'''<section class="contact-banner section"><div class="wrap"><div class="reveal"><p class="eyebrow">Persönlich. Regional. Kompetent.</p><h2>Gute Technik beginnt<br>mit einem Gespräch<span class="dot">.</span></h2></div><div class="reveal"><p>Was soll Ihre Technik für Sie leisten? Sprechen wir über Ihr Unternehmen und Ihre nächsten Schritte.</p>{btn('kontakt',base,'Kontakt aufnehmen')}</div></div></section>'''
def shell(title,description,content,base,current):
 return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#102849"><title>{esc(title)} | SL Service</title><meta name="description" content="{esc(description)}"><link rel="icon" href="{base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{base}assets/style.css"><script defer src="{base}assets/main.js"></script></head><body>{header(base,current)}<main id="inhalt">{content}</main>{footer(base)}{support(base)}</body></html>'''
def breadcrumb(base,title,parent=None):return f'<nav class="breadcrumb wrap" aria-label="Brotkrumennavigation">{link("",base,"Startseite")}<span aria-hidden="true">/</span>'+((link(parent,base)+'<span aria-hidden="true">/</span>') if parent else '')+f'<span aria-current="page">{title}</span></nav>'
def feature_grid(items):return '<div class="feature-grid">'+''.join(f'<div class="feature"><h3>{t}</h3><p>{p}</p></div>' for t,p in items)+'</div>'
def side(base):return f'<aside class="side-panel"><p class="eyebrow">Sprechen wir darüber</p><h3>Ihre Frage.<br>Unser nächster Schritt.</h3><p>Wir freuen uns auf Ihr Anliegen und besprechen gemeinsam die passende Lösung.</p><a href="tel:+4998515825890">09851 58258-90</a><a href="mailto:info@sl-sv.de">info@sl-sv.de</a>{btn("kontaktformular",base,"Anfrage vorbereiten")}</aside>'
def service_index(slugs,base):
 return '<div class="service-index">'+''.join(f'<a href="{href(s,base)}"><small>{i+1:02}</small><div><h3>{PAGES[s]["title"]}</h3><p>{PAGES[s]["lead"]}</p></div><span aria-hidden="true">↗</span></a>' for i,s in enumerate(slugs))+'</div>'
def related(slugs,base):return '<section class="section related"><div class="wrap"><p class="eyebrow">Weitergedacht</p><h2>Das könnte Sie<br>auch interessieren<span class="dot">.</span></h2><div class="link-grid">'+''.join(f'<a class="link-card" href="{href(s,base)}"><small>{PAGES[s]["group"]}</small><h3>{PAGES[s]["title"]}</h3><p>{PAGES[s]["lead"]}</p><span aria-hidden="true">↗</span></a>' for s in slugs)+'</div></div></section>'

def home(base):return f'''<section class="hero"><img class="hero-image" src="{base}assets/it-hero.webp" alt="Illustratives Bildmotiv: Techniker an einer Netzwerkumgebung" width="1672" height="941" fetchpriority="high"><div class="wrap hero-inner"><p class="eyebrow">IT & Sicherheitstechnik · Dinkelsbühl</p><h1>Ihre IT läuft<span class="dot">.</span><br>Ihre Sicherheit steht<span class="dot">.</span></h1><p class="hero-intro">Technik, die Ihr Unternehmen weiterbringt.</p><div class="actions">{btn('kontakt',base,'Projekt besprechen')}<a class="text-link" href="#leistungen">Unsere Leistungen <span aria-hidden="true">↓</span></a></div></div><a class="support-card" href="tel:+4998515825890"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M6 3 3 5c0 9 7 16 16 16l2-3-5-4-2 2c-3-1-5-3-6-6l2-2-4-5Z"/></svg><span><small>Direkter Support</small><strong>09851 58258-90</strong></span><span class="arrow" aria-hidden="true">↗</span></a></section><div class="service-strip"><span>IT-INFRASTRUKTUR</span><span>DATENSCHUTZBETREUUNG</span><span>SICHERHEITSTECHNIK</span></div>
<section class="section wrap" id="leistungen"><div class="section-head reveal"><div><p class="eyebrow">Unsere Leistungen</p><h2>Zwei Kompetenzen<span class="dot">.</span><br>Ein verlässlicher Partner<span class="dot">.</span></h2></div><p>Wir verbinden moderne IT mit professioneller Sicherheitstechnik – für Unternehmen in Dinkelsbühl und der Region.</p></div><div class="service-cards"><a class="service-card reveal" href="{href('it-dienstleistungen',base)}"><div class="photo"><img src="{base}assets/it-hero.webp" alt="Illustrative Netzwerk- und Servertechnik" width="1672" height="941" loading="lazy"></div><div class="card-body"><div class="card-heading"><h3>IT-Dienstleistungen</h3><span aria-hidden="true">↗</span></div><div class="card-facts"><span>Netzwerke<small>Planung und Umsetzung</small></span><span>Telekommunikation<small>Verbunden arbeiten</small></span><span>IT-Service<small>Persönlich betreut</small></span></div></div></a><a class="service-card reveal" href="{href('sicherheitstechnik',base)}"><div class="photo"><img src="{base}assets/security.webp" alt="Illustrative Kamera an einem Geschäftsgebäude" width="1672" height="941" loading="lazy"></div><div class="card-body"><div class="card-heading"><h3>Sicherheitstechnik</h3><span aria-hidden="true">↗</span></div><div class="card-facts"><span>Videoüberwachung<small>Überblick behalten</small></span><span>Zutrittskontrolle<small>Zugänge gezielt steuern</small></span><span>Gefahrenmeldetechnik<small>Schutz sinnvoll planen</small></span></div></div></a></div><a class="privacy-band reveal" href="{href('datenschutzbetreuung',base)}"><b>Datenschutzbetreuung</b><p>Klarheit für den Umgang mit Daten.</p><span aria-hidden="true">↗</span></a></section>
<section class="process section"><div class="wrap"><p class="eyebrow">Von der Frage zur Lösung</p><h2>Verstehen. Umsetzen.<br>Weiter begleiten<span class="dot">.</span></h2><div class="process-grid"><div class="process-item reveal"><span>01 / BERATUNG</span><h3>Ihr Unternehmen verstehen.</h3><p>Was benötigen Ihre Menschen und Ihre Abläufe? Gemeinsam klären wir die Anforderungen.</p></div><div class="process-item reveal"><span>02 / REALISIERUNG</span><h3>Technik sinnvoll verbinden.</h3><p>Aus den Anforderungen wird eine passende Lösung für IT, Kommunikation oder Gebäudesicherheit.</p></div><div class="process-item reveal"><span>03 / BETREUUNG</span><h3>Auch danach an Ihrer Seite.</h3><p>Mit persönlichen Ansprechpartnern und Unterstützung bei Ihren technischen Fragen.</p></div></div></div></section>
<section class="section wrap company-split"><img class="company-photo reveal" src="{base}assets/company.webp" alt="Illustratives Motiv für persönliche IT-Beratung" loading="lazy" width="1672" height="941"><div class="company-copy reveal"><p class="eyebrow">SL Service kennenlernen</p><h2>Regional verbunden<span class="dot">.</span><br>Technisch vielseitig<span class="dot">.</span></h2><p>Seit 2003 unterstützt SL Service Unternehmen in der Region. Von Netzwerk und Arbeitsplatz bis zur Gebäudesicherheit: Wir denken Ihre Technik im Zusammenhang.</p><div class="sector-list"><span>Handwerk & Industrie</span><span>Handel & Hotellerie</span><span>Verwaltung & Institutionen</span></div>{link('vorstellung',base,'Mehr über SL Service ↗','text-link')}</div></section>{cta(base)}'''

def contact_form():return '''<form class="contact-form"><h2>Ihr Anliegen<span class="dot">.</span></h2><div class="form-row"><label>Name *<input name="name" required autocomplete="name"></label><label>Unternehmen<input name="company" autocomplete="organization"></label></div><div class="form-row"><label>E-Mail *<input type="email" name="email" required autocomplete="email"></label><label>Telefon<input type="tel" name="phone" autocomplete="tel"></label></div><label>Worum geht es?<select name="topic"><option>IT-Dienstleistungen</option><option>Sicherheitstechnik</option><option>Datenschutzbetreuung</option><option>Allgemeine Anfrage</option></select></label><label>Ihre Nachricht *<textarea name="message" required maxlength="4000"></textarea></label><button class="btn" type="submit">E-Mail vorbereiten <span aria-hidden="true">↗</span></button><p class="form-note">* Erforderliche Angaben. Das Formular speichert und versendet nichts. Im nächsten Schritt können Sie die vorbereitete Nachricht in Ihrem E-Mail-Programm öffnen und selbst versenden.</p><div class="form-status" role="status" aria-live="polite"></div></form>'''

def special(slug,base):
 if slug in ['kontakt','kontaktformular']:
  return f'<div class="contact-layout"><div><p class="eyebrow">Direkt verbunden</p><h2>Sprechen wir<br>miteinander<span class="dot">.</span></h2><a class="contact-detail" href="tel:+4998515825890">09851 58258-90 ↗</a><a class="contact-detail" href="mailto:info@sl-sv.de">info@sl-sv.de ↗</a><p>SL Service und Verwaltungs GmbH<br>Innovativ-Ring 1<br>91550 Dinkelsbühl</p><div class="hours"><span>Montag–Donnerstag</span><span>08:00–16:00 Uhr</span><span>Freitag</span><span>08:00–14:00 Uhr</span></div><div class="actions">{link("ansprechpartner",base,"Ansprechpartner ↗","text-link")}{link("standort",base,"Anfahrt ↗","text-link")}</div></div>{contact_form()}</div>'
 if slug=='ansprechpartner':
  persons=[('AS','Geschäftsführung','Andreas Schott','+4998515825821','09851 58258-21','a.schott@sl-i.de'),('GL','Geschäftsführung','Gerhard Lierheimer','+4998515825820','09851 58258-20','g.lierheimer@sl-i.de'),('DM','Prokuristin','Daniela Müller','+4998515825890','09851 58258-90','d.mueller@sl-sv.de'),('JD','IT-Dienstleistungen','Jens Delert','+4998515825890','09851 58258-90','j.delert@sl-sv.de'),('TZ','Sicherheitstechnik','Thomas Zosel','+4998515825890','09851 58258-90','t.zosel@sl-sv.de')]
  return '<div class="contacts">'+''.join(f'<article class="person"><div class="initial" aria-hidden="true">{initial}</div><small>{role}</small><h3>{name}</h3><a href="tel:{tel}">{num} ↗</a><a href="mailto:{mail}">{mail}</a></article>' for initial,role,name,tel,num,mail in persons)+'</div>'
 if slug in ['standort','support']:
  if slug=='standort':return f'<div class="content-grid"><div class="prose"><h2>Innovativ-Ring 1<span class="dot">.</span></h2><p>SL Service und Verwaltungs GmbH<br>Innovativ-Ring 1, Waldeck<br>91550 Dinkelsbühl</p><p>Besprechen Sie Ihren Besuch gerne vorab telefonisch mit uns.</p><a class="btn" href="https://www.google.com/maps/search/?api=1&query=Innovativ-Ring+1+91550+Dinkelsb%C3%BChl" target="_blank" rel="noopener noreferrer">Route in Google Maps öffnen ↗</a><p class="form-note">Die Karte wird erst beim Öffnen des externen Links geladen.</p>{link("ansprechpartner",base,"Ihre Ansprechpartner ↗","text-link")}</div>{side(base)}</div>'
  return f'<div class="content-grid"><div class="prose"><h2>Persönlicher Support<span class="dot">.</span></h2><p>Telefon: <a href="tel:+4998515825890">09851 58258-90</a><br>E-Mail: <a href="mailto:support@sl-sv.de">support@sl-sv.de</a></p><div class="hours"><span>Montag–Donnerstag</span><span>08:00–16:00 Uhr</span><span>Freitag</span><span>08:00–14:00 Uhr</span></div><h2>Fernwartung nach Absprache.</h2><p>Bitte stimmen Sie eine Fernwartung zuerst mit unserem Support ab. Das bestehende Fernwartungsprogramm wird über die Original-Website bereitgestellt.</p><a class="btn" href="https://www.sl-sv.de/files/SL-SV/Download/Software/SL_Fernwartung.exe">Bestehende Fernwartung herunterladen ↗</a><p class="form-note">Externer Download von sl-sv.de. Der Download startet nur durch Ihren Klick.</p></div>{side(base)}</div>'
 return None

def standard(slug,base):
 p=PAGES[slug];security=p['group']=='Sicherheit';image='security' if security else ('company' if p['group'] in ['Unternehmen','Kontakt','Karriere','Datenschutz'] or slug=='beratung' else 'it-hero')
 parent='sicherheitstechnik' if security and slug!='sicherheitstechnik' else ('it-dienstleistungen' if p['group']=='IT' and slug!='it-dienstleistungen' else None)
 intro=breadcrumb(base,p['title'],parent)+f'<section class="page-hero"><div class="wrap"><div><p class="eyebrow">{p["group"]} · SL Service</p><h1>{p["title"]}<span class="dot">.</span></h1><p>{p["lead"]}</p>{btn("kontakt",base,"Sprechen wir darüber")}</div><figure><img class="hero-{image.split("-")[0]}" src="{base}assets/{image}.webp" alt="Illustratives Konzeptmotiv zur {"Sicherheitstechnik" if security else "IT-Betreuung"}" width="1672" height="941"></figure></div></section>'
 body=special(slug,base)
 if body is None:
  content=f'<h2>{p["heading"]}</h2><p>{p["text"]}</p>'+feature_grid(p['features'])
  if slug=='it-dienstleistungen':content+=service_index(IT,base)
  if slug=='sicherheitstechnik':content+=service_index(SEC,base)
  if slug=='sl-service':content+=service_index(COMP,base)
  if slug=='sl-service/branchen-loesungen':content+=feature_grid([(x,'IT-Umgebung und Sicherheitstechnik gemeinsam auf Ihre Arbeitsabläufe abstimmen.') for x in ['Handwerk & Industrie','Handel','Gastronomie & Hotellerie','Öffentliche Verwaltung','Kirchliche Institutionen','Arztpraxen']])
  if slug=='vorstellung':content+=f'{link("ansprechpartner",base,"Ihre Ansprechpartner kennenlernen ↗","text-link")}'
  if slug=='karriere':content+=f'<div class="service-index"><a href="{href("job/ausbildung-elektroniker-in-fuer-gebaeude-und-infrastruktursysteme-m-w-d",base)}"><small>01</small><div><h3>Ausbildung Elektroniker/in</h3><p>Geräte und Systeme · m/w/d · Dinkelsbühl</p></div><span>↗</span></a></div><h2>Initiativ bewerben.</h2><p>Erzählen Sie uns, was Sie begeistert und welche Erfahrung Sie mitbringen. Ihre Bewerbungsunterlagen können Sie per E-Mail oder Post übermitteln.</p><a class="btn" href="mailto:bewerbung@sl-sv.de">Bewerbung per E-Mail ↗</a><p class="form-note">Bitte aktuelle Stellenverfügbarkeit und Konditionen direkt beim Unternehmen erfragen.</p>'
  if slug.startswith('job/'):content+='<a class="btn" href="mailto:bewerbung@sl-sv.de?subject=Anfrage%20zur%20Ausbildung">Ausbildung anfragen ↗</a>'
  body=f'<div class="content-grid"><div class="prose">{content}</div>{side(base)}</div>'
 rel=SEC[:3] if security else IT[:3]
 if p['group']=='Unternehmen':rel=['ansprechpartner','karriere','sl-service/branchen-loesungen']
 rel=[s for s in rel if s!=slug][:3]
 return intro+f'<section class="section wrap">{body}</section>'+related(rel,base)+cta(base)

def blog(base):
 cards=''
 for slug,title,date,category,text,target in ARTICLES:
  pic='security' if category=='Sicherheit' else 'it-hero'
  visual=(f'<div class="blog-image {"it" if pic=="it-hero" else ""}"><img src="{base}assets/{pic}.webp" alt="Illustratives Themenmotiv" loading="lazy" width="1672" height="941"></div>' if category!='Unternehmen' else '<div class="blog-image letters" aria-hidden="true">SL<span class="dot">.</span></div>')
  cards+=f'<article class="blog-card" data-category="{category}">{visual}<div class="body"><small>{date} · {category}</small><h3>{title}</h3><a class="text-link" href="{href(slug,base)}">Zum Beitrag <span aria-hidden="true">↗</span></a></div></article>'
 cards+=f'<article class="blog-card" data-category="IT"><div class="blog-image it"><img src="{base}assets/it-hero.webp" alt="Illustrative IT-Infrastruktur" loading="lazy"></div><div class="body"><small>14.01.2020 · IT</small><h3>Backup-as-a-Service</h3>{link("Backup",base,"Zum Beitrag ↗","text-link")}</div></article>'
 return breadcrumb(base,'Blog & Archiv')+f'<section class="section wrap"><p class="eyebrow">Wissen & Einblicke</p><h1>Technik. Menschen.<br>Neuigkeiten<span class="dot">.</span></h1><p class="archive">Archiv der auf der bestehenden Website veröffentlichten Beiträge. Daten und historische Themen bleiben erkennbar; frühere Partnerschaften oder Angebote sind keine Aussage über den heutigen Stand.</p><div class="blog-tools"><div class="filters">'+''.join(f'<button class="filter" data-filter="{x}" aria-pressed="{str(x=="Alle").lower()}">{x}</button>' for x in ['Alle','IT','Sicherheit','Unternehmen'])+f'</div><input class="blog-search" type="search" aria-label="Blogbeiträge durchsuchen" placeholder="Beiträge durchsuchen …"></div><p class="archive" id="result-count">13 Beiträge</p><div class="blog-grid">{cards}</div><p class="empty-message" hidden>Keine passenden Beiträge. Versuchen Sie einen anderen Suchbegriff.</p></section>'+cta(base)

def article(a,base):
 slug,title,date,category,text,target=a;pic='security' if category=='Sicherheit' else 'it-hero'
 return breadcrumb(base,title)+f'<section class="section wrap"><article class="article"><p class="eyebrow">{category} · Archiv</p><h1>{title}<span class="dot">.</span></h1><p class="date">Veröffentlicht am {date}</p>'+ (f'<img class="article-photo {"it" if pic=="it-hero" else ""}" src="{base}assets/{pic}.webp" alt="Illustratives Themenmotiv – kein Originalfoto des Ereignisses" width="1672" height="941">' if category!='Unternehmen' else '')+f'<p>{text}</p><p class="archive">Archivansicht zur Kundenvorstellung. Der Beitrag ist redaktionell gekürzt. Den vollständigen historischen Inhalt finden Sie auf der bestehenden Website.</p><a class="text-link" href="https://www.sl-sv.de/de/{slug}.html" target="_blank" rel="noopener noreferrer">Originalbeitrag öffnen ↗</a><div class="article-navigation">{link("news",base,"← Zurück zum Archiv")}{link(target,base,"Passende Leistung kennenlernen ↗")}</div></article></section>'+cta(base)

def legal(slug,base):
 title={'impressum':'Impressum','datenschutz':'Datenschutz','agb':'Allgemeine Geschäftsbedingungen'}[slug]
 content=''
 if slug=='impressum':content='''<h2>Unternehmensangaben</h2><p>SL Service und Verwaltungs GmbH<br>Innovativ-Ring 1, Waldeck<br>91550 Dinkelsbühl<br>Telefon: 09851 58258-90<br>Fax: 09851 58258-98<br>E-Mail: info@sl-sv.de</p><h2>Vertretung & Register</h2><p>Geschäftsführer laut bestehendem Impressum: Gerhard Lierheimer und Andreas Schott.<br>Registergericht Ansbach: HRB 3696<br>Umsatzsteuer-ID: DE 231 685 460</p><div class="notice">Diese Seite ist ein privater Design- und Funktionsentwurf zur Kundenvorstellung, kein offizieller neuer Internetauftritt von SL Service. Die Unternehmensangaben stammen aus dem bestehenden Impressum und sind vor der offiziellen Veröffentlichung zu bestätigen. Die Bildmotive sind KI-generierte Illustrationen; sie zeigen keine tatsächlichen Mitarbeiter oder Geschäftsräume.</div><h2>Bestehendes Impressum</h2><p>Die vollständigen Hinweise der aktuellen Unternehmenswebsite sind weiterhin dort abrufbar.</p><a href="https://www.sl-sv.de/de/impressum.html" target="_blank" rel="noopener noreferrer">Aktuelles Unternehmensimpressum öffnen ↗</a>'''
 if slug=='datenschutz':content='''<div class="notice">Diese Präsentationsversion ist noch kein offizieller Unternehmensauftritt. Für einen späteren Livegang muss die Datenschutzerklärung an den tatsächlichen Betreiber, das endgültige Hosting und die aktivierten Dienste angepasst werden.</div><h2>Technik dieser Präsentationsversion</h2><p>Die Website verwendet lokal bereitgestellte Bilder, Stylesheets und Skripte. Es werden keine Google Fonts, Analyse- oder Marketingdienste, eingebetteten Karten oder Social-Media-Plugins geladen. Der Website-Code setzt keine eigenen Cookies und verwendet weder Local Storage noch Session Storage.</p><h2>Formulare und Kontakt</h2><p>Das Kontaktformular verarbeitet Ihre Eingaben nur im Browser, um einen E-Mail-Entwurf vorzubereiten. Es speichert keine Daten auf einem eigenen Server und versendet nichts automatisch. Erst wenn Sie den E-Mail-Link öffnen und selbst versenden, erfolgt die Verarbeitung über Ihr E-Mail-Programm und die beteiligten E-Mail-Anbieter. Telefon- und E-Mail-Links öffnen die entsprechenden Funktionen Ihres Geräts.</p><h2>Hosting und externe Links</h2><p>Diese private Vorschau wird über ChatGPT Sites bereitgestellt. Beim Abruf erhält die Hostinginfrastruktur technisch notwendige Verbindungsdaten, etwa die IP-Adresse. Zugang und Plattformverarbeitung richten sich nach den Informationen von OpenAI. Externe Zielseiten werden erst beim Öffnen ihrer Links aufgerufen; dort gelten deren Datenschutzinformationen.</p><p><a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer">Datenschutzinformationen von OpenAI ↗</a></p><h2>Offizielle Unternehmenswebsite</h2><p>Die bestehende Datenschutzerklärung von SL Service gilt für deren aktuellen Internetauftritt und ist dort abrufbar. Sie wird nicht ungeprüft auf diese technisch abweichende Präsentationsversion übertragen.</p><a href="https://www.sl-sv.de/de/datenschutz.html" target="_blank" rel="noopener noreferrer">Bestehende Datenschutzerklärung öffnen ↗</a>'''
 if slug=='agb':content='''<h2>Die Bedingungen der Zusammenarbeit.</h2><p>Die bestehenden Allgemeinen Geschäftsbedingungen von SL Service stehen auf der aktuellen Unternehmenswebsite als PDF zum Download bereit.</p><a class="btn" href="https://www.sl-sv.de/files/SL-SV/Download/Allgemein/AGB%20SL%20Service%202022.pdf" target="_blank" rel="noopener noreferrer">Bestehende AGB als PDF öffnen ↗</a><p><a href="https://www.sl-sv.de/de/agb.html" target="_blank" rel="noopener noreferrer">Alternativ zur offiziellen AGB-Seite ↗</a></p><div class="notice">Der Entwurf verändert keine Vertragsbedingungen. Die endgültigen Dokumente sind vor einem offiziellen Livegang vom Unternehmen freizugeben.</div>'''
 return breadcrumb(base,title)+f'<section class="section wrap"><div class="legal"><p class="eyebrow">Informationen</p><h1>{title}<span class="dot">.</span></h1>{content}</div></section>'

def write(slug,title,desc,render):
 path=OUT/('index.html' if not slug else 'de/'+slug+'.html');path.parent.mkdir(parents=True,exist_ok=True)
 base=os.path.relpath(OUT,path.parent).replace('\\','/')+'/'
 if base=='./':base=''
 path.write_text(shell(title,desc,render(base),base,slug),encoding='utf-8')

write('','IT & Sicherheitstechnik in Dinkelsbühl','SL Service – Ihr regionales Systemhaus für IT, Kommunikation und Sicherheitstechnik. Website-Entwurf.',home)
write('index','IT & Sicherheitstechnik in Dinkelsbühl','SL Service – Ihr regionales Systemhaus.',home)
for slug,p in PAGES.items():write(slug,p['title'],p['lead'],lambda b,s=slug:standard(s,b))
write('news','Blog & Archiv','Historische Beiträge zu SL Service, IT und Sicherheitstechnik.',blog)
for a in ARTICLES:write(a[0],a[1],a[4],lambda b,a=a:article(a,b))
for slug in ['impressum','datenschutz','agb']:write(slug,slug.capitalize(),'Informationen zur Präsentationsversion.',lambda b,s=slug:legal(s,b))
(OUT/'404.html').write_text(shell('Seite nicht gefunden','Die gesuchte Seite konnte nicht gefunden werden.','<section class="section wrap"><p class="eyebrow">404</p><h1>Hier geht es<br>nicht weiter.</h1><p>Zurück zur Startseite oder zu unseren Leistungen.</p>'+btn('','','Zur Startseite')+'</section>','',''),encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
(OUT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#243d7c"/><text x="9" y="42" font-size="30" font-family="Arial" font-weight="bold" fill="white">SL</text><circle cx="53" cy="48" r="5" fill="#fb861a"/></svg>')
inventory=[dict(path=str(f.relative_to(OUT)),title=('Startseite' if f.name=='index.html' else f.stem)) for f in OUT.rglob('*.html')]
(ROOT/'page-inventory.json').write_text(json.dumps(inventory,ensure_ascii=False,indent=2))
print(f'Built {len(inventory)} HTML pages')
